/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACol: typeof import('ant-design-vue/es')['Col']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARow: typeof import('ant-design-vue/es')['Row']
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    Content: typeof import('./src/components/layout.vue/Content.vue')['default']
    Footer: typeof import('./src/components/layout.vue/Footer.vue')['default']
    Header: typeof import('./src/components/layout.vue/Header.vue')['default']
    Layout: typeof import('./src/components/layout.vue/Layout.vue')['default']
    PageHeader: typeof import('./src/components/pageHeader/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/layout.vue/Sider.vue')['default']
    Slider: typeof import('./src/components/slider/Slider.vue')['default']
  }
}
